Add controllers
oleg-bobrikov/java-shareit pull request #1
Opened 2023-08-07 19:49 UTC by oleg-bobrikov

2023-08-08 10:52 UTC, TomattmanYandex requested changes
Комменты в коде
Мне очень не нравится использование примитивов везде где надо и не надо
а еще очень сильно перемудрил в репозитории прям очень сильно

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private int id;
используем обертки вместо примитивов, как минимум в таких полях

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private LocalDate start;
я бы дал более понятные имена, типа startDate endDate

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final Map<Integer, Map<Integer, Item>> itemsByOwnerId = new HashMap<>();
зачем хранить сразу три мапы, а две еще внутри которых мапы

не проще ли просто обойти все значения, из одной и вернуть те которые нужны, три мапы это три разных источника данных, и если где то забудешь в одну что то записать, то данные уже будут не консистентно

тем более это решение на условно один спринт

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto pathItem(ItemDto itemDto) {
неправильно имя метода написал

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.searchByOwnerId(ownerId).stream().map(itemMapper::toDto).collect(Collectors.toList());
можно в маппере создатьь метод, который будет принимать лист обьектов, и возвращать лист дто, и он по маппингу одного обьекта сдлеает автоматический маппинг списка

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +package ru.practicum.shareit.user.model;
зачем выкидывать один класс модели в отдельный пакет, это имеет смысл с дто, так как их будет много на некоторые классы, но модель при таком разбиении на пакеты может лежать вместе с остальными классами

2023-08-08 10:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private int id;
я уже писал про это

2023-08-08 17:07 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private int id;
Заменен int на Integer

2023-08-08 17:07 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private LocalDate start;
startDate, endDate

2023-08-08 17:09 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final Map<Integer, Map<Integer, Item>> itemsByOwnerId = new HashMap<>();
цель была реализовать поиск данных за O(1).
Другие варианты реализуют доступ за O(N).

2023-08-08 17:10 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final Map<Integer, Map<Integer, Item>> itemsByOwnerId = new HashMap<>();
Понятно, что можно сделать все через stream и делать обход O(N)

2023-08-08 17:11 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final Map<Integer, Map<Integer, Item>> itemsByOwnerId = new HashMap<>();
когда подключится база данных, реализация хранилища будет лаконичнее и красивее.

2023-08-08 17:13 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto pathItem(ItemDto itemDto) {
спасибо, поправил на patchItem

2023-08-08 17:22 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +package ru.practicum.shareit.user.model;
удалил пакет model

2023-08-08 17:23 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private int id;
заменил на обертку

2023-08-08 18:11 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        return itemRepository.searchByOwnerId(ownerId).stream().map(itemMapper::toDto).collect(Collectors.toList());
реализовано через метод
 List<ItemDto> toDtoList(List<Item> item);

2023-08-09 08:29 UTC, TomattmanYandex approved these changes
Принято

2023-08-09 08:29 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private Integer id;
чаще в качестве идентификаторов используют вообще Long

2023-08-18 18:17 UTC, merged