sprint 14 jpa
oleg-bobrikov/java-shareit pull request #2
Opened 2023-09-03 12:46 UTC by oleg-bobrikov

2023-09-04 09:34 UTC, TomattmanYandex requested changes
вопросов много, переделать надо много, 
также надо сделать скрипт создающий структуру базы, который будет ее и создавать

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
чаще используют LocalDate или LocalDateTime

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
А еще стоит дать имя получше переменной, что за старт, время старта, галочка что стартануло, или еще какие ни будь варианты

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
и следующая переменная так же

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(length = 8)
Зачем тут length = 0

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    List<BookingAnswerDto> toDtoList(List<Booking> bookings);
лучше просто перегрузить метод toDto

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByItem_Owner_IdAndStatusOrderByStartDesc(Long ownerId, Status status);
Лично я очень не люблю использование нижних подчеркиваний в именах репозиторных методов, ибо это именование вообще не в стиле джавы

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (start.isBefore(now)) {
1 валидацию можно вынести в отдельный метод
2 BusinessLogicException плохое имя, ибо по нему вообще ничего не понятно для чего ошибка, по сути это либо валидация падает, либо некорректные данные

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Item item = itemRepository.findByIdPessimisticRead(bookingRequestDto.getItemId())
можно использовать itemservice и его метод поиска по id ведь он сам по себе бросит ошибку если обьект будет не найден

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User booker = userRepository.findByIdPessimisticRead(bookingRequestDto.getBookerId())
то же самое и с пользователем

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!item.getIsAvailable()) {
и снова валидация, которую можно вынести в отдельный метод

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findById(bookingApproveDto.getBookingId())
вот тут можно было бы периспользовать метода поиска по id

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User user = userRepository.findById(bookingGetDto.getUserId())
зачем при получении букинга нам проверять пользователя, пользователя надо проверить при создании букинга, а потом уже считать что он есть, тем более ограничения базы данных не позволят удалить пользователя без удаления связанного букинга

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!booking.getItem().getOwner().getId().equals(user.getId()) &&
прочитать эту конструкцию очень нелегко, и понять тем более, проще было бы вынести в переменные и использовать оттуда

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    ALL, CURRENT, PAST, FUTURE, WAITING, REJECTED
что за статусы Current и Past зачем они здесь

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    ALL, CURRENT, PAST, FUTURE, WAITING, REJECTED
и future

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingApproveDto.java
> +    Long ownerId;
модификаторы доступа

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingGetByStateDto.java
> +    Long bookerId;
модификаторы

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingGetDto.java
> +
пустая строчка, модификаторы

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/converter/StateConverter.java
> +public class StateConverter {
зачем нужен этот класс и метод, если это все есть втстроенное в enum

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/BusinessLogicException.java
> +public class BusinessLogicException extends RuntimeException {
Про название этой ошибки я уже писал

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/SqlException.java
> +public class SqlException extends RuntimeException {
кажется у спринга уже есть sqlException и за что будет отвечать эта ошибка?

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    private OffsetDateTime created = OffsetDateTime.now();
про тип я уже писал

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findAllByItem_Id(Long itemId);
про нижние подчеркивания я уже писал

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_READ)
круто, если ты понимаешь что это значит)

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemGetRequestDto.java
> +public class ItemGetRequestDto {
на Get запросы обычно нету тела запроса, точно правильное название класса?

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemPatchRequestDto.java
> +public class ItemPatchRequestDto {
чем он отличается от ItemPostRequestDto может тут тоже нужна валидация, и можно оставить поле с id  и тогда оставить один класс dto

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/itemrequest/ItemRequest.java
> +    private Instant created = Instant.now();
про даты я уже писал

2023-09-04 09:34 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        } catch (DataIntegrityViolationException exception) {
сложноватая конструкция, почему бы, ели не падает ошибка, просто не прокинуть ее дальше, а потом уже в обработчике ошибок обработать как надо

2023-09-05 19:03 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
> чаще используют LocalDate или LocalDateTime

В случае, если серверное время Postman отличается от серверного времени приложения,
то может возникать ошибка.
В моем приложении в базу данных записывается время UTC.
LocalDateTime для этого не подходит, так как Java Core возвращает локальное время с учетом часового пояса.

2023-09-05 19:15 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
> А еще стоит дать имя получше переменной, что за старт, время старта, галочка что стартануло, или еще какие ни будь варианты

В модельном классе Booking 
start переименован в start_date

2023-09-05 19:16 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
> и следующая переменная так же

в модельном классе Booking
end переименован в endDate

2023-09-05 19:21 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(length = 8)
> Зачем тут length = 0
ORM Spring hibernate создает базу данных автоматически по аннотациям.
Аннотация @Enumerated(EnumType.STRING) означает, что ENUM  в базе данных будет храниться 
в виде типа String.
Есть еще вариант в виде числового значения.
В Postgresql для Java String соответствует тип Varchar(255).
Поскольку используемый enum при конвертации в String ограничен длиной в 8 символов,
то нет необходимости хранить избыточные данные в СУБД Postgresql.

2023-09-05 19:39 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    List<BookingAnswerDto> toDtoList(List<Booking> bookings);
> лучше просто перегрузить метод toDto

Перегрузка метода toDo() не получится, так как для этого нужна сигнатура, отличная от существующей.
Для этого нужно либо изменить количество аргументов, либо изменить тип аргумента.
Поскольку тип аргумента не меняется, так как это модельный класс, то вводить еще один аргумент нет никакого смысла.

2023-09-05 19:42 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByItem_Owner_IdAndStatusOrderByStartDesc(Long ownerId, Status status);
> Лично я очень не люблю использование нижних подчеркиваний в именах репозиторных методов, ибо это именование вообще не в стиле джавы

Метод изначально был сгенерирован идеей как запросный.
Переименовал в findAllByItemOwnerIdAndStatusOrderByStartDateDesc.
Тесты ошибок не выдали.

2023-09-05 19:52 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (start.isBefore(now)) {
> 1 валидацию можно вынести в отдельный метод 2 BusinessLogicException плохое имя, ибо по нему вообще ничего не понятно для чего ошибка, по сути это либо валидация падает, либо некорректные данные

Валидация вынесена в отдельный метод
 private void validatePeriod(Instant startDate, Instant endDate) 
 
BusinessLogicException заменен на PeriodValidationException

2023-09-05 20:05 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Item item = itemRepository.findByIdPessimisticRead(bookingRequestDto.getItemId())
> можно использовать itemservice и его метод поиска по id ведь он сам по себе бросит ошибку если обьект будет не найден

itemService Работает с DTO, а не с моделью, 
поэтому понадобится дополнительный маппинг.
Кроме того, в создании бронирования нужна целостность данных, а именно:
пользователь не должен быть удален во время создания бронирования.
Все действия должны быть выполнены в  транзакции, 
пользователь должен быть заблокирован для удаления.
Этого можно достичь 2 способами,
1) установить аннотацию @transactional(isolaton= Isolation.Serialazibale)
2)использовать @transactionl ( что соответствует уровню изоляции read commited) и пессимистическую блокировку.
3) использовать оптимистическую блокировку и аннтотацию @Retryable

2023-09-05 20:21 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User booker = userRepository.findByIdPessimisticRead(bookingRequestDto.getBookerId())
> то же самое и с пользователем

Для создания модели Booking требуется модель item и user.
Дополнительная конвертация из DTO будет нагружать сервис.

2023-09-05 20:31 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        User user = userRepository.findById(bookingGetDto.getUserId())
> зачем при получении букинга нам проверять пользователя, пользователя надо проверить при создании букинга, а потом уже считать что он есть, тем более ограничения базы данных не позволят удалить пользователя без удаления связанного букинга

Это связано с тем, что BookingAnswerDto  может быть поддельная, и идентификатор пользователя вымышленный.
В Postman есть специальная проверка для этого.
Кроме того запросить бронирование может либо пользователь, который забронировал, либо владелец вещи.
` if (!booking.getItem().getOwner().getId().equals(user.getId()) &&
                !booking.getBooker().getId().equals(user.getId())) {
            throw new NotFoundException("User with id " + bookingGetDto.getUserId() + " is not valid.");
        }`
        Именно для этого нужно проверить, есть ли вообще такой пользователь.

2023-09-05 20:56 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!booking.getItem().getOwner().getId().equals(user.getId()) &&
> прочитать эту конструкцию очень нелегко, и понять тем более, проще было бы вынести в переменные и использовать оттуда

`
        long ownerId = booking.getItem().getOwner().getId();
        long userId = user.getId();
        long bookerId = booking.getBooker().getId();
        if (!(userId == ownerId || userId == bookerId)) {
            throw new NotFoundException("User with id " + bookingGetDto.getUserId() + " is not valid.");
        }`

2023-09-05 21:21 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Item item = itemRepository.findByIdPessimisticRead(bookingRequestDto.getItemId())
Есть еще одна проблема - 
класс сервис на верхний уровень, то есть на уровень котроллера, должен возвращать DTO, но не модели.
Класс репозитория возвращает модели.
Когда один класс сервиса вызывает методы другого, то приходится делать маппинг DTO в модель и обратно.
Это дополнительные накладные расходы.
Повторяющиеся методы вынес отдельно:

`    private User findUserById(long userId) {
        return userRepository.findByIdPessimisticRead(userId)
                .orElseThrow(() -> new NotFoundException("User with id " + userId + " is not exist"));
    }

    private Booking findBookingById(long bookingId) {
        return bookingRepository.findById(bookingId)
                .orElseThrow(() -> new NotFoundException("Booking with id " + bookingId + " is not exist"));
    }`

2023-09-05 21:22 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!item.getIsAvailable()) {
вынесена в отдельный метод

2023-09-05 21:24 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    ALL, CURRENT, PAST, FUTURE, WAITING, REJECTED
Это не статусы, а состояния. 
Сделано по ТЗ 14.

2023-09-05 21:27 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingApproveDto.java
> +    Long ownerId;
добавлен private модификатор

2023-09-05 21:28 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingGetDto.java
> +
> пустая строчка, модификаторы

удалена пустая строчка, добавлен private

2023-09-05 21:34 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/converter/StateConverter.java
> +public class StateConverter {
> зачем нужен этот класс и метод, если это все есть втстроенное в enum

Если бы все так было просто. 
Postman не устраивает MethodArgumentNotValidException со статусом 400 для проверки корректности переданного статуса в контроллере в процессе сериализации. Он ожидает специальное сообщение "Unknown state:"
Для этого был создан отдельный обработчик
UnsupportedStateException, а в контроллере, чтобы избежать ошибки сериализации enum был заменен на String.

2023-09-05 21:35 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/exception/BusinessLogicException.java
> +public class BusinessLogicException extends RuntimeException {
Это исключение удалено.

2023-09-05 21:50 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    private OffsetDateTime created = OffsetDateTime.now();
> 

В ТЗ была рекомендация использовать Timestamp для БД.
Также реализована концепция UTC

2023-09-05 22:00 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/CommentRepository.java
> +    List<Comment> findAllByItem_Id(Long itemId);
удалено подчеркивание

2023-09-05 22:02 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_READ)
Об этом я уже писал, это пессимистическая блокировка используется в транзакции  с уровнем изоляции
read commited.

2023-09-05 22:03 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/itemrequest/ItemRequest.java
> +    private Instant created = Instant.now();
> про даты я уже писал

Рекомендация была использовать Timestamp.
В приложении реализован UTC

2023-09-05 22:14 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        } catch (DataIntegrityViolationException exception) {
> сложноватая конструкция, почему бы, ели не падает ошибка, просто не прокинуть ее дальше, а потом уже в обработчике ошибок обработать как надо

Перенесен обработчик в CustomExceptionHandler

2023-09-05 22:17 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/dto/ItemPatchRequestDto.java
> +public class ItemPatchRequestDto {
> 
В ItemPostRequestDto как раз реализована валидация через нотации.
В ItemPatchRequestDto валидация не треубется

2023-09-05 22:25 UTC, oleg-bobrikov commented on src/main/java/ru/practicum/shareit/item/dto/ItemGetRequestDto.java
> +public class ItemGetRequestDto {
> на Get запросы обычно нету тела запроса, точно правильное название класса?

объект нужен был, чтобы один аргумент был.
Удалил эту DTO

2023-09-06 18:25 UTC, oleg-bobrikov commented
> вопросов много, переделать надо много,
> также надо сделать скрипт создающий структуру базы, который будет ее и создавать



> вопросов много, переделать надо много, также надо сделать скрипт создающий структуру базы, который будет ее и создавать



> опросов много, переделать надо много,
> также надо сделать скрипт создающий структуру базы, который будет ее и создавать

cкрипт создан

2023-09-07 11:19 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private OffsetDateTime start;
При чем тут время в постмане? он только клиент для работы с бэкендом

2023-09-07 11:27 UTC, TomattmanYandex approved these changes
пару коментов оставил, но не критические
принято

2023-09-07 11:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(length = 8)
окок, мне показалось что там было значение 0

2023-09-07 11:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    List<BookingAnswerDto> toDtoList(List<Booking> bookings);
тип аргумента различный, в первом методе это один обьект, в этом методе лист обьектов

2023-09-07 11:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/dto/BookingGetByStateDto.java
> +   private Long bookerId;
сьехало форматирование

2023-09-07 18:58 UTC, merged